### ISSUE TITLE
Find by MAC address

### ISSUE THREAD

**Issue by anthonycastelli** [PeteLawrence/homebridge-people#6]
I've find IP address on my network frequently change. If its possible, maybe you can implement a way to look up devices by mac address then get the IP and ping it. I know you can run arp -a to get a list of IPS and mac address on a network.

**Comment by PeteLawrence** [comment]
Thanks for the feedback.  AFAIK the arp table only contains the IP's/mac addresses of devices that have sent traffic to the local device recently, so it wouldn't work for those devices that don't communicate directly with the device running homebridge.

I don't see any reason why you couldn't use a hostname instead of an IP address in the config file, I'll give this a shot later when I'm home and if it works I'll update the documentation accordingly.  The other option is to set up reservations on your router/DHCP server.

**Comment by PeteLawrence** [comment]
Just checked and there's nothing to stop you setting IP to be a hostname, as long as that hostname can be resolved from the device running homebridge.  I've updated the module and documentation and replaced references to 'ip' with 'target' for clarification.
